name: Docker Build & Push

on:
    workflow_dispatch: {}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
# Comment
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-app:latest -f docker-python-app-code/Dockerfile .
          docker tag ${{ secrets.DOCKER_USERNAME }}/demo-app:latest \
          ${{ secrets.DOCKER_USERNAME }}/demo-app:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:${{ github.sha }}