name: Multi Job Workflow Demo 2

on:
  workflow_dispatch: {}

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Job One Step
        run: echo "This is Job One"

  job-two:
    needs: job-one
    runs-on: ubuntu-latest
    steps:
      - name: Job Two Step
        run: echo "This is Job Two and runs after Job One"